//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarAnnouncement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarAnnouncement()
        {
            this.Comments = new HashSet<Comment>();
        }
    
        public int ID { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> CarProductionDate { get; set; }
        public Nullable<decimal> CarMotor { get; set; }
        public string About { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> CarModelID { get; set; }
        public Nullable<int> CarGearID { get; set; }
        public Nullable<int> CarFuelID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<bool> IsVIP { get; set; }
        public Nullable<int> ColorID { get; set; }
        public Nullable<int> Ride { get; set; }
        public Nullable<int> Price { get; set; }
        public string Title { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual Fuel Fuel { get; set; }
        public virtual Gearbox Gearbox { get; set; }
        public virtual Model Model { get; set; }
        public virtual City City { get; set; }
        public virtual Color Color { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
    }
}
